# Site settings
title: Dataplexity.eu
description: Scientific data visualizations
baseurl: "" # the subpath of your site, e.g. /blog
url: dataplexity.eu # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Silvio
user_description: My cause: securing human rights in the digital world.
project_description: Below find my portfolio.
user_title: CEO
email: s.heinze@dataplexity.org
twitter_username: twitter_username
github_username: github_username

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
