# Site settings
title: Dataplexity.eu
description: Scientific data visualizations
baseurl: "" # the subpath of your site, e.g. /blog
url: dataplexity.eu # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dataplexity.eu
user_description: We provide new perspectives on social issues on data.
project_description: Projects
user_title: an all new perspective on data
email: s.heinze@dataplexity.org

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
